# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

find_apr_rcpp <- function(dna_seq, minAPR = 4L, maxAPR = 9L, minATracts = 3L) {
    .Call(`_gfaR_find_apr_rcpp`, dna_seq, minAPR, maxAPR, minATracts)
}

find_dr_rcpp <- function(dna_seq, mindir = 10L, maxdir = 100L, dspacer = 100L) {
    .Call(`_gfaR_find_dr_rcpp`, dna_seq, mindir, maxdir, dspacer)
}

find_gq_rcpp <- function(dna_seq, minGQ = 3L, maxGQspacer = 7L) {
    .Call(`_gfaR_find_gq_rcpp`, dna_seq, minGQ, maxGQspacer)
}

find_ir_rcpp <- function(dna_seq, mincrf = 6L, cspacer = 100L, cut = 9L, shortSpacer = 4L) {
    .Call(`_gfaR_find_ir_rcpp`, dna_seq, mincrf, cspacer, cut, shortSpacer)
}

find_mr_rcpp <- function(dna_seq, minmir = 10L, mspacer = 100L) {
    .Call(`_gfaR_find_mr_rcpp`, dna_seq, minmir, mspacer)
}

find_str_rcpp <- function(dna_seq, minSTR = 1L, maxSTR = 6L, minSTRlen = 10L, minReps = 3L) {
    .Call(`_gfaR_find_str_rcpp`, dna_seq, minSTR, maxSTR, minSTRlen, minReps)
}

find_zdna_rcpp <- function(dna_seq, minZ = 10L) {
    .Call(`_gfaR_find_zdna_rcpp`, dna_seq, minZ)
}

