// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// find_apr_rcpp
DataFrame find_apr_rcpp(std::string dna_seq, int minAPR, int maxAPR, int minATracts);
RcppExport SEXP _gfaR_find_apr_rcpp(SEXP dna_seqSEXP, SEXP minAPRSEXP, SEXP maxAPRSEXP, SEXP minATractsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type dna_seq(dna_seqSEXP);
    Rcpp::traits::input_parameter< int >::type minAPR(minAPRSEXP);
    Rcpp::traits::input_parameter< int >::type maxAPR(maxAPRSEXP);
    Rcpp::traits::input_parameter< int >::type minATracts(minATractsSEXP);
    rcpp_result_gen = Rcpp::wrap(find_apr_rcpp(dna_seq, minAPR, maxAPR, minATracts));
    return rcpp_result_gen;
END_RCPP
}
// find_dr_rcpp
DataFrame find_dr_rcpp(std::string dna_seq, int mindir, int maxdir, int dspacer);
RcppExport SEXP _gfaR_find_dr_rcpp(SEXP dna_seqSEXP, SEXP mindirSEXP, SEXP maxdirSEXP, SEXP dspacerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type dna_seq(dna_seqSEXP);
    Rcpp::traits::input_parameter< int >::type mindir(mindirSEXP);
    Rcpp::traits::input_parameter< int >::type maxdir(maxdirSEXP);
    Rcpp::traits::input_parameter< int >::type dspacer(dspacerSEXP);
    rcpp_result_gen = Rcpp::wrap(find_dr_rcpp(dna_seq, mindir, maxdir, dspacer));
    return rcpp_result_gen;
END_RCPP
}
// find_gq_rcpp
DataFrame find_gq_rcpp(std::string dna_seq, int minGQ, int maxGQspacer);
RcppExport SEXP _gfaR_find_gq_rcpp(SEXP dna_seqSEXP, SEXP minGQSEXP, SEXP maxGQspacerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type dna_seq(dna_seqSEXP);
    Rcpp::traits::input_parameter< int >::type minGQ(minGQSEXP);
    Rcpp::traits::input_parameter< int >::type maxGQspacer(maxGQspacerSEXP);
    rcpp_result_gen = Rcpp::wrap(find_gq_rcpp(dna_seq, minGQ, maxGQspacer));
    return rcpp_result_gen;
END_RCPP
}
// find_ir_rcpp
DataFrame find_ir_rcpp(std::string dna_seq, int mincrf, int cspacer, int cut, int shortSpacer);
RcppExport SEXP _gfaR_find_ir_rcpp(SEXP dna_seqSEXP, SEXP mincrfSEXP, SEXP cspacerSEXP, SEXP cutSEXP, SEXP shortSpacerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type dna_seq(dna_seqSEXP);
    Rcpp::traits::input_parameter< int >::type mincrf(mincrfSEXP);
    Rcpp::traits::input_parameter< int >::type cspacer(cspacerSEXP);
    Rcpp::traits::input_parameter< int >::type cut(cutSEXP);
    Rcpp::traits::input_parameter< int >::type shortSpacer(shortSpacerSEXP);
    rcpp_result_gen = Rcpp::wrap(find_ir_rcpp(dna_seq, mincrf, cspacer, cut, shortSpacer));
    return rcpp_result_gen;
END_RCPP
}
// find_mr_rcpp
DataFrame find_mr_rcpp(std::string dna_seq, int minmir, int mspacer);
RcppExport SEXP _gfaR_find_mr_rcpp(SEXP dna_seqSEXP, SEXP minmirSEXP, SEXP mspacerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type dna_seq(dna_seqSEXP);
    Rcpp::traits::input_parameter< int >::type minmir(minmirSEXP);
    Rcpp::traits::input_parameter< int >::type mspacer(mspacerSEXP);
    rcpp_result_gen = Rcpp::wrap(find_mr_rcpp(dna_seq, minmir, mspacer));
    return rcpp_result_gen;
END_RCPP
}
// find_str_rcpp
DataFrame find_str_rcpp(std::string dna_seq, int minSTR, int maxSTR, int minSTRlen, int minReps);
RcppExport SEXP _gfaR_find_str_rcpp(SEXP dna_seqSEXP, SEXP minSTRSEXP, SEXP maxSTRSEXP, SEXP minSTRlenSEXP, SEXP minRepsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type dna_seq(dna_seqSEXP);
    Rcpp::traits::input_parameter< int >::type minSTR(minSTRSEXP);
    Rcpp::traits::input_parameter< int >::type maxSTR(maxSTRSEXP);
    Rcpp::traits::input_parameter< int >::type minSTRlen(minSTRlenSEXP);
    Rcpp::traits::input_parameter< int >::type minReps(minRepsSEXP);
    rcpp_result_gen = Rcpp::wrap(find_str_rcpp(dna_seq, minSTR, maxSTR, minSTRlen, minReps));
    return rcpp_result_gen;
END_RCPP
}
// find_zdna_rcpp
DataFrame find_zdna_rcpp(std::string dna_seq, int minZ);
RcppExport SEXP _gfaR_find_zdna_rcpp(SEXP dna_seqSEXP, SEXP minZSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type dna_seq(dna_seqSEXP);
    Rcpp::traits::input_parameter< int >::type minZ(minZSEXP);
    rcpp_result_gen = Rcpp::wrap(find_zdna_rcpp(dna_seq, minZ));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_gfaR_find_apr_rcpp", (DL_FUNC) &_gfaR_find_apr_rcpp, 4},
    {"_gfaR_find_dr_rcpp", (DL_FUNC) &_gfaR_find_dr_rcpp, 4},
    {"_gfaR_find_gq_rcpp", (DL_FUNC) &_gfaR_find_gq_rcpp, 3},
    {"_gfaR_find_ir_rcpp", (DL_FUNC) &_gfaR_find_ir_rcpp, 5},
    {"_gfaR_find_mr_rcpp", (DL_FUNC) &_gfaR_find_mr_rcpp, 3},
    {"_gfaR_find_str_rcpp", (DL_FUNC) &_gfaR_find_str_rcpp, 5},
    {"_gfaR_find_zdna_rcpp", (DL_FUNC) &_gfaR_find_zdna_rcpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_gfaR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
